inputs:
  - class: Pipe
    enabled: false
    author: Pipe
  - class: Prompt
    enabled: true
    author: Prompt
  - class: Shell
    enabled: true
    author: Shell
    shell: echo 'Hello, world!'
outputs:
  - class: Stdout
    enabled: true
  - class: RocketChat
    enabled: false
    channel: '#general'
    uri: https://open.rocket.chat
    user: 'rc_user'
    pass: 'Pa55w0rd'
